name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "adopt-hotspot"
          java-version: "8"

      - run: wget -q -O apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar 

      - run: java -jar apktool.jar b .

      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: dist/ims.apk
